In [33]:
import csv
import pygal
from pygal.style import Style
import pandas as pd
from IPython.display import SVG, HTML, display
from country_codes import get_country_code

In [16]:
filename = "../data/covid-death-confirmed.csv"
df = pd.read_csv(filename)
df

,date,confirmed,deaths,recovered,country,pop_2018,percent_deaths
0,2021-05-11,62403,2710,54503,Afghanistan,37172386.0,4.342740
1,2021-05-11,131803,2420,119061,Albania,2866376.0,1.836074
2,2021-05-11,124483,3343,86703,Algeria,42228429.0,2.685507
3,2021-05-11,13447,127,13070,Andorra,77006.0,0.944449
4,2021-05-11,29146,639,25145,Angola,30809762.0,2.192411
...,...,...,...,...,...,...,...
186,2021-05-11,3571,35,2618,Vietnam,95540395.0,0.980118
187,2021-05-11,302777,3393,287932,West Bank and Gaza,4569087.0,1.120627
188,2021-05-11,6492,1276,3003,Yemen,0.0,19.654960
189,2021-05-11,92152,1258,90539,Zambia,17351822.0,1.365136
190,2021-05-11,38448,1579,36221,Zimbabwe,14439018.0,4.106846

In [17]:
def get_index(v):
    if v < 5:
        return 0
    if v < 10: 
        return 1
    if v < 20:
        return 2
    
    return 3

In [18]:
cc_population = [dict() for x in range(4)]

for index, row in df.iterrows():
    code = get_country_code(row['country'])
    if code:
        p = row['percent_deaths']
        cc_population[get_index(p)][code] = p
    else:
        print(f"no code for /{row['country']}/ found")

no code for /Antigua and Barbuda/ found
no code for /Bahamas/ found
no code for /Barbados/ found
no code for /Burma/ found
no code for /Cabo Verde/ found
no code for /Comoros/ found
no code for /Congo (Brazzaville)/ found
no code for /Congo (Kinshasa)/ found
no code for /Diamond Princess/ found
no code for /Dominica/ found
no code for /Eswatini/ found
no code for /Fiji/ found
no code for /Grenada/ found
no code for /Holy See/ found
no code for /Kosovo/ found
no code for /MS Zaandam/ found
no code for /Marshall Islands/ found
no code for /Micronesia/ found
no code for /Saint Kitts and Nevis/ found
no code for /Saint Lucia/ found
no code for /Saint Vincent and the Grenadines/ found
no code for /Samoa/ found
no code for /Solomon Islands/ found
no code for /Taiwan*/ found
no code for /Tanzania/ found
no code for /Trinidad and Tobago/ found
no code for /Vanuatu/ found
no code for /West Bank and Gaza/ found

In [38]:
custom_style = Style(
    font_family='googlefont:Raleway',
    tooltip_font_size=8
)

In [40]:
wm = pygal.maps.world.World(height=300, style=custom_style)
labels = [".lt.  5%", ".lt. 10%", ".lt. 20%", "more than 20%"]

wm.title = "World Deaths of Confirmed Cases, by Country"
for idx in range(0, len(labels)):
    if cc_population[idx]:
        wm.add(labels[idx], cc_population[idx])
    
wm.render_to_file('covid.svg')